# Generated by Django 4.0.6 on 2022-08-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IBK', 'IBK 산업은행'), ('KEB', 'KEB 하나은행')], max_length=100, unique=True)),
            ],
        ),
    ]
