# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TTS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TTS
  pod 'Then'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'Moya/RxSwift'
  pod 'Charts'

  target 'TTSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TTSUITests' do
    # Pods for testing
  end

end
