# Generated by Django 4.0.6 on 2022-08-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount'),
        ('power_plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerplant',
            name='bank_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bankaccount'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
